STANDARD_CUSTOM_FIELDS = {
	"Item": [
		{
			"fieldname": "custom_mrp_default_stock_buffer",
			"label": "Default MRP Stock Buffer",
			"fieldtype": "Link",
			"options": "MRP Stock Buffer",
			"insert_after": "lead_time_days",
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection MRP. Default buffer controls MRP lead time.",
		},
		{
			"fieldname": "custom_mrp_lead_time_days",
			"label": "MRP Lead Time Days",
			"fieldtype": "Int",
			"insert_after": "custom_mrp_default_stock_buffer",
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection MRP. Used on ERPNext versions without native Item Lead Time Days.",
		},
	],
	"Material Request": [
		{
			"fieldname": "custom_mrp_run",
			"label": "MRP Run",
			"fieldtype": "Link",
			"options": "MRP Run",
			"insert_after": "schedule_date",
			"allow_on_submit": 1,
			"read_only": 1,
			"in_list_view": 1,
			"no_copy": 1,
			"description": "Owned by Injection MRP.",
		},
		{
			"fieldname": "custom_mrp_requirement",
			"label": "MRP Requirement",
			"fieldtype": "Link",
			"options": "MRP Requirement Line",
			"insert_after": "custom_mrp_run",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection MRP.",
		},
		{
			"fieldname": "custom_mrp_commitment_type",
			"label": "MRP Commitment Type",
			"fieldtype": "Select",
			"options": "\nPrebuy\nFirm",
			"insert_after": "custom_mrp_requirement",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection MRP.",
		},
		{
			"fieldname": "custom_mrp_consumed_qty",
			"label": "MRP Consumed Qty",
			"fieldtype": "Float",
			"insert_after": "custom_mrp_commitment_type",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection MRP.",
		},
		{
			"fieldname": "custom_mrp_remaining_qty",
			"label": "MRP Remaining Qty",
			"fieldtype": "Float",
			"insert_after": "custom_mrp_consumed_qty",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection MRP.",
		},
		{
			"fieldname": "custom_aps_run",
			"label": "APS Run",
			"fieldtype": "Link",
			"options": "APS Planning Run",
			"insert_after": "custom_mrp_remaining_qty",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection MRP.",
		},
		{
			"fieldname": "custom_aps_result",
			"label": "APS Result",
			"fieldtype": "Link",
			"options": "APS Schedule Result",
			"insert_after": "custom_aps_run",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection MRP.",
		},
	],
	"Material Request Item": [
		{
			"fieldname": "custom_mrp_run",
			"label": "MRP Run",
			"fieldtype": "Link",
			"options": "MRP Run",
			"insert_after": "schedule_date",
			"allow_on_submit": 1,
			"read_only": 1,
			"in_list_view": 1,
			"no_copy": 1,
			"description": "Owned by Injection MRP.",
		},
		{
			"fieldname": "custom_mrp_requirement",
			"label": "MRP Requirement",
			"fieldtype": "Link",
			"options": "MRP Requirement Line",
			"insert_after": "custom_mrp_run",
			"allow_on_submit": 1,
			"read_only": 1,
			"in_list_view": 1,
			"no_copy": 1,
			"description": "Owned by Injection MRP.",
		},
		{
			"fieldname": "custom_mrp_commitment_type",
			"label": "MRP Commitment Type",
			"fieldtype": "Select",
			"options": "\nPrebuy\nFirm",
			"insert_after": "custom_mrp_requirement",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection MRP.",
		},
		{
			"fieldname": "custom_mrp_consumed_qty",
			"label": "MRP Consumed Qty",
			"fieldtype": "Float",
			"insert_after": "custom_mrp_commitment_type",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection MRP.",
		},
		{
			"fieldname": "custom_mrp_remaining_qty",
			"label": "MRP Remaining Qty",
			"fieldtype": "Float",
			"insert_after": "custom_mrp_consumed_qty",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection MRP.",
		},
		{
			"fieldname": "custom_aps_run",
			"label": "APS Run",
			"fieldtype": "Link",
			"options": "APS Planning Run",
			"insert_after": "custom_mrp_remaining_qty",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection MRP.",
		},
		{
			"fieldname": "custom_aps_result",
			"label": "APS Result",
			"fieldtype": "Link",
			"options": "APS Schedule Result",
			"insert_after": "custom_aps_run",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection MRP.",
		},
		{
			"fieldname": "custom_mrp_supplier",
			"label": "MRP Supplier",
			"fieldtype": "Link",
			"options": "Supplier",
			"insert_after": "custom_aps_result",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection MRP.",
		},
		{
			"fieldname": "custom_mrp_supplier_quotation",
			"label": "MRP Supplier Quotation",
			"fieldtype": "Link",
			"options": "Supplier Quotation",
			"insert_after": "custom_mrp_supplier",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection MRP.",
		},
		{
			"fieldname": "custom_mrp_item_price",
			"label": "MRP Item Price",
			"fieldtype": "Link",
			"options": "Item Price",
			"insert_after": "custom_mrp_supplier_quotation",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection MRP.",
		},
		{
			"fieldname": "custom_mrp_estimated_rate",
			"label": "MRP Estimated Rate",
			"fieldtype": "Currency",
			"insert_after": "custom_mrp_item_price",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection MRP.",
		},
		{
			"fieldname": "custom_mrp_estimated_amount",
			"label": "MRP Estimated Amount",
			"fieldtype": "Currency",
			"insert_after": "custom_mrp_estimated_rate",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection MRP.",
		},
		{
			"fieldname": "custom_mrp_procurement_summary",
			"label": "MRP Procurement Summary",
			"fieldtype": "Small Text",
			"insert_after": "custom_mrp_estimated_amount",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection MRP.",
		},
	],
}

MRP_OWNED_PAGE_NAMES = [
	"mrp-demand-console",
	"mrp-material-workbench",
	"mrp-pegging-detail",
	"mrp-shortage-timeline",
	"mrp-run-console",
	"mrp-release-center",
]

MRP_OWNED_RECORDS = {
	"Workspace": ["Injection MRP"],
	"Page": MRP_OWNED_PAGE_NAMES,
}


def get_standard_custom_field_names():
	names = []
	for doctype, fields in STANDARD_CUSTOM_FIELDS.items():
		for field in fields:
			names.append(f"{doctype}-{field['fieldname']}")
	return names
